### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by peternewman**
See e.g. https://travis-ci.com/peternewman/midimonster/builds/102847793

You'll need to enable your repo on https://travis-ci.com for the full benefit.

The Mac build is currently broken, you can either fix it, or it can be flagged as allowed failure for now.

The bleeding edge clang is not being used for sanitizing currently as you force the variable to be "clang".

### CODE REVIEW

**Comment by peternewman** [comment]
See e.g. https://travis-ci.com/peternewman/midimonster/builds/102846620

You'll need to enable your repo on https://travis-ci.com for the full benefit.

The Mac build is currently broken, you can either fix it, or it can be flagged as allowed failure for now.

I'm not sure that the bleeding edge clang is being used for sanitizing currently.

**Comment by cbdevnet** [comment]
Thanks for taking the effort! I just enabled Travis for the Repo :)

The `sanitize` target is not that important, I just use it to find stuff that static analysis can catch easily before uploading to Coverity.

**Comment by cbdevnet** [comment]
The build failure seems to be that OSX does not have `CLOCK_MONOTONIC_COARSE`, but that should already be handled in [https://github.com/cbdevnet/midimonster/blob/master/portability.h#L2]. Does the compiler Travis is using export `__APPLE__`? Or is there another feature-test macro for that?

**Comment by cbdevnet** [comment]
Ah, just realized the Macro is not currently being used. Will fix that this evening

**Pull request merged**
