### PR TITLE
PRH examples

### PR DESCRIPTION
**Pull request by phedders**
I've created a couple of useful lua scripts that others might find helpful on their own or to see how the lua routines work

### CODE REVIEW

**Comment by cbdevnet** [comment]
Wow, thats some very cool stuff! I'll try out some of those, too!

Thanks  a lot! :)

**Comment by phedders** [comment]
On Wed, 2021-01-13 at 12:41 -0800, cbdev wrote:
> Wow, thats some very cool stuff! I'll try out some of those, too!
> Thanks a lot! :)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Sweet. I'm sorry to mess you about but I'm merging some of my smaller
"utils" into one utils.lua - so i might be push another PR soon. The
others are silly really "returnzero" does just that, "onlyone" will
only trigger on 1.0 input etc.

I have pondered a feature request for maps such that you can define
value filter/limit and or value translations, it would be neater than
lua hacks, but the lua hacks work well for now, so I'll submit the full
list of them in one bundle. Since the same script can be used with
multiple backend+default definitions, it works well for me.

**Comment by cbdevnet** [comment]
I have some plans for filters that may be applied to channel mappings directly in the core (such as `invert`/`edge detect`/`toggle`/etc), but that's in the future (ie. version 1.1 and later). So in the meantime, lua and/or python will stay the best method for doing that. I know that it's a bit cumbersome though...

I've also thought about creating a kind of "standard library" for the Lua scripts, so maybe a utils.lua would be a nice base for that :) You're welcome to add more PRs, I'm always happy to see that people enjoy the MIDIMonster :)

**Comment by phedders** [comment]
On Wed, 2021-01-13 at 12:53 -0800, cbdev wrote:
> I have some plans for filters that may be applied to channel mappings
> directly in the core (such as invert/edge detect/toggle/etc), but
> that's in the future (ie. version 1.1 and later). So in the meantime,
> lua and/or python will stay the best method for doing that. I know
> that it's a bit cumbersome though...
> I've also thought about creating a kind of "standard library" for the
> Lua scripts, so maybe a utils.lua would be a nice base for that :)
> You're welcome to add more PRs, I'm always happy to see that people
> enjoy the MIDIMonster :)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Yea I'd like to submit a couple of docs tweaks too actually come to
think of it - just to help others with a few areas I got stuck on for a
while.

The prime one is that when you set a default-handler (function), that
is the *only* function you can call with that backend set and the
channel you give is in available through input_channel(). That gives a
lot of power because it is effectively giving another variable other
than the value - and I'm using it a lot now, but it was confusing me
for ages! The next game changer was realising I can then do multiple
[lua ...] to the same script to give access to the other functions.

I'm only scratching the surface - but really enjoying what I can do
with MM.
ie it that v3 trackpad hack is really nice. v1 had a horrible tangle of
nested if's which sucked and was totally inflexible. A little maths
made it very simple and very powerful. To be able to map a complex
gesture to a trigger or command with just one line.... so nice!

**Pull request merged**
